### ISSUE TITLE
combining unicode characters

### ISSUE THREAD

**Issue by aloispichler** [ggandor/leap.nvim#190] opened 2023-10-08 09:54 UTC
The plugin ignores everything what comes after a combining unicode character :-( .

**Comment by ggandor** [comment] 2023-10-08 16:28
I think that issue has been fixed (see https://github.com/ggandor/leap.nvim/issues/108). Could you give a reproducible example?

**Comment by aloispichler** [comment] 2023-10-08 18:45
In this file, I am searching for `test` by typing (with regular config) `s` first, then `t` (first picture) and then `e` (second picture). The plugin the gets stuck.

First screenshot:
![Screenshot_2023-10-08_20-37-49](https://github.com/ggandor/leap.nvim/assets/45781387/5d2084e7-ff49-4da4-b2e4-a619a53c9707)

Second screenshot:
![Screenshot_2023-10-08_20-38-05](https://github.com/ggandor/leap.nvim/assets/45781387/04567639-d91e-49aa-83b0-292de1ce3037)

The file contains two combined characters: ₀᪲   (in  ∫₀᪲ ) and ‖⃰  in (‖⋅‖⃰ ).

**Comment by ggandor** [comment] 2023-10-09 10:12
I cannot reproduce, the plugin finds everything correctly even after using those fancy characters. Could you copy/paste the buffer content instead of screenshots, for a sanity check?

**Comment by ggandor** [comment] 2024-02-22 14:06
Closed by 847a740 (should work on stable versions too now).

**Closed by ggandor** 2024-02-22 14:06 UTC
