### ISSUE TITLE
The cursor didn't show at the first matched place? Any hint~~

### ISSUE THREAD

**Issue by LintaoAmons** [ggandor/leap.nvim#71] opened 2022-10-23 13:02 UTC
As shown in the `gif`, I don't know why my cursor stayed, but actually it have changed it's position to the matched place.

- My terminal `wezterm`
- Nvim 8.0

![leap](https://user-images.githubusercontent.com/95092244/197393549-821fe4d2-67ff-44ce-937e-27bbb5be9906.gif)

**Comment by ggandor** [comment] 2022-10-23 15:15
Yep, this is super annoying, 0.8 introduced this bug, I'm clueless at the moment. Duplicate of #70 :)

**Closed by ggandor** 2022-10-23 15:15 UTC

**Comment by ggandor** [comment] 2022-10-23 15:16
But you should see the "fake" cursor anyway. It seems the `Cursor` highlight group is not defined. See #27.
